version: '3.8'

services:
  serviceregistry:
    build:
      context: ./ServiceRegistry
      dockerfile: docker/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - scaler-network

  productservice:
    build:
      context: ./ScalerBackendProject
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/first_web?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://serviceregistry:8761/eureka/
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_AUTOCONFIGURE_EXCLUDE=
    depends_on:
      - serviceregistry
      - mysql
      - redis
      - kafka
    networks:
      - scaler-network

  discoveryclient:
    build:
      context: ./DiscoveryClient
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - serviceregistry
    networks:
      - scaler-network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=first_web
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - scaler-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - scaler-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - scaler-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - scaler-network

networks:
  scaler-network:
    driver: bridge

volumes:
  mysql_data:
